---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-api-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - secrets
      - deployments
      - statefulsets
      - statefulsets/scale
    verbs:
      - create
      - delete
      - get
      - list
      - watch
      - update
  - apiGroups:
      - "apps"
    resources:
      - pods
      - services
      - endpoints
      - secrets
      - deployments
      - statefulsets
      - statefulsets/scale
    verbs:
      - create
      - delete
      - get
      - list
      - watch
      - update
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-api-role
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:serviceaccount:k8s-api-role:default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-api-role
subjects:
- kind: ServiceAccount
  name: k8s-api-role
  namespace: default
