apiVersion: v1
kind: Service
metadata:
  name: ccnm-fe-server
spec:
  selector:
    app: L-ccnm-fe-server
  {{- if eq .Values.global.IsCloud "old" }}
  ports:
    - name: http-9090
      protocol: TCP
      port: 9090
      targetPort: 80
  externalIPs:
  - {{ .Values.global.PubIp }}
  {{- end }}
  {{- if eq .Values.global.IsCloud "yes" }}
  type: NodePort
  ports:
    - port: 80
{{- if .Values.global.NoNodePortHardcoding }}
{{- else }}
      nodePort: 36022
{{- end }}
      name: 9090-tcp
  {{- end }}
  {{- if eq .Values.global.IsCloud "no" }}
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
      name: 9090-tcp
  {{- end }}

