kind: Service
apiVersion: v1
metadata:
  name: registrar
spec:
  selector:
    app: registrar
  type: NodePort
  ports:
    - port: 34409
      name: 34409-tcp
{{- if .Values.global.NoNodePortHardcoding }}
{{- else }}
      nodePort: 36648
{{- end }}
