kind: Service
apiVersion: v1
metadata:
  name: ff-grpc-restapi-conversion
spec:
  selector:
    app: L-ff-grpc-restapi-conversion
  {{- if eq .Values.global.IsCloud "old" }}
  ports:
    - name: http-8088
      protocol: TCP
      port: 8088
      targetPort: 8088
  externalIPs:
    - {{ .Values.global.PubIp }}
  {{- end }}
  {{- if eq .Values.global.IsCloud "yes" }}
  type: NodePort
  ports:
    - port: 8088
{{- if .Values.global.NoNodePortHardcoding }}
{{- else }}
      nodePort: 36023
{{- end }}
      name: http-8088
  {{- end }}
  {{- if eq .Values.global.IsCloud "no" }}
  type: LoadBalancer
  ports:
    - port: 8088
      protocol: TCP
      targetPort: 8088
      name: http-8088
  {{- end }}
