apiVersion: batch/v1
kind: Job
metadata:
  name: csodb-schema
  labels:
    app: csodb-schema
spec:
  backoffLimit: 30
  template:
    metadata:
      labels:
        app: csodb-schema
    spec:
      imagePullSecrets:
        - name: cnhubcred
      containers:
      - name: csodb-schema
        imagePullPolicy: IfNotPresent
        image: celona/celona-csodb-schema:{{ .Chart.Version }}
        env:
        - name: DB_HOST
          value: "{{ .Values.CfgmDbHost }}"
        - name: DB_NAME
          value: "{{ .Values.CfgmDbName }}"        
        - name: DB_ENV
          value: "{{ .Values.DbEnv }}"
        - name: DB_USERNAME
          value: "{{ .Values.CfgmDbUser }}"        
        - name: DB_PASSWORD
          value: "{{ .Values.CfgmDbPassword }}"
        - name: DB_SUFFIX
          value: "{{ .Values.DbSuffix }}"
        - name: HOOKSENABLED
          value: "{{ .Values.HooksEnabled }}"
      restartPolicy: Never
      nodeSelector:
        nodetype: worker
