---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-registry-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-registry-role
rules:
- apiGroups:
  - extensions
  resources:
  - deployments
  - daemonsets
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - daemonsets
  - replicasets
  - statefulsets/scale
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - namespaces
  - services
  - podtemplates
  verbs:
  - watch
  - list
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-registry-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-registry-role
subjects:
- kind: ServiceAccount
  name: service-registry-sa
  namespace: default
